### ISSUE TITLE
CMAKE_MODULE_PATH append not set

### ISSUE THREAD

**Issue by Lightnet** [RobLoach/raylib-lua-sol#37]
Your CMakeLists.txt has an error.
`set(CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")`
to
`list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")`
I am using addon for easy to setup by using FetchContent.

**Comment by RobLoach** [comment]
Good catch! Submitted a PR for it 👍
